### ISSUE TITLE
Refactor comments in code

### ISSUE THREAD

**Issue by matwasilewski** [everycure-org/matrix#454]
This ticket is intended as an invitation to a discussion about code style (specifically as it pertains to comments in code). 

# What's wrong with comments?
A comment left in the code should be a last resort attempt at explaining the underlying logic, rather than a crutch for poor code with badly divided abstraction layers. Comments are bad because:
- **They often lie**: Comment is not what is being executed - code is. One-line explanations often fail to capture nuances of the underlying logic, and they might outright lie about what is happening. Just look into the code.
- **They often become outdated**: Comments are expansive to maintain, and there is no mechanism that ensures code and comments stay in alignment. It has been my experience again and again that even the best comments in beloved codebases would become outdated.
- **Code should speak for itself**: Code should consist of properly named, self-explanatory functions. Comments are often used to cover bad and convoluted code - if your function needs a comment to explain what it does, you should probably refactor.
- **Comments add clutter**: Comments add visual clutter, making reading the codebase more difficult than it needs to be.
- **Comments are maintenance overhead**: They are not free - they take time to maintain. If on a tight deadline, comments will be the first thing to be ignored, leading to them becoming untrue and obsolete, cluttering the codebase and distorting what functions do.

_My opinionated approach to comments in code (and to code style more broadly) is heavily influenced by Robert Martin's Clean Code, which I highly recommend._

**Martin's rules on comments**
- Always try to explain yourself in code.
- Don't be redundant.
- Don't add obvious noise.
- Don't use closing brace comments.
- Don't comment out code. Just remove.
- Use as explanation of intent.
- Use as clarification of code.
- Use as warning of consequences.

Below is an incomplete list of issues I found with EC's comments in code.

# Task List
- [ ] Agree on best practices wrt. comments
- [ ] Refactor accordingly
- [ ] Write Style Guide, and add to documentation
- [ ] Make a follow up issue to add linter (ruff?) that would pick up commented out code

# Comment review
## Comments are too verbose

```python

class LazySparkDataset(SparkDataset):
    """Lazy loading spark datasets to avoid loading spark every run.

    A trick that makes our spark loading lazy so we never initiate
    """

    def _load(self):
        SparkHooks._initialize_spark()
        return super()._load()

```

What does this docstring add to the code? The fact that it is Lazy Loaded dataset is implied in the name of the class.

`A trick that makes our spark loading lazy so we never initiate` also does not add everything - we can assume that a developer knows what Lazy Loading is, or at the very least can ask GPT about it.

## Comments describe file

Almost every file in the codebase starts with a comment, indicating what this file does. No - name of the file should imply that.

```python
"""Embeddings pipeline."""
from kedro.pipeline import Pipeline, node, pipeline

from . import nodes
```

It is called `embeddings/pipeline.py` , and contains one function called `create_pipeline` . I have guessed that it is Embeddings Pipeline, and this docstring added to my life nothing but visual clutter, unecessary code lines and the soul crushing awareness that it will have to be maintained.

Or: 

```python
"""Matrix init file."""

__version__ = "0.1"
```

In `__init__.py` .

OR

```python
"""Pair generator module.

Module containing drug-disease pair generator
"""
import abc
from tqdm import tqdm
import pandas as pd
import random
from kedro.io import AbstractDataset

from matrix.datasets.graph import KnowledgeGraph

from typing import List, Set

class DrugDiseasePairGenerator(abc.ABC):
    """Generator strategy class to represent drug-disease pair generators."""
```

`"""Pair generator module.` → The module is called `pair_generator.py`

`Module containing drug-disease pair generator` yes, very appropriately and verbosely named (we love to see it!) class called `DrugDiseasePairGenerator` is ten lines below.

## Comments that are missing

Sometimes, important comments are missing.

For example, `pipeline_registry.py`  and it’s `register_pipelines()` function have a special meaning in Kedro, and will result in registering those pipelines without being called anywhere explicitly. It would be easier to understand the codebase if we added a comment about that to either the file or function.

```python
def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        Mapping from a pipeline name to a ``Pipeline`` object.
    """
    pipelines = {}
```

## Commented out code

From `matrix.pipelines.matrix.tests.pipelines.test_pipelines.py` 

```python
@pytest.mark.integration
# @pytest.mark.skipif(
#     os.environ.get("CI") == "true", reason="Ongoing issue with the Kedro catalog"
# )
# skipping due to dynamic pipelines not being supported at the moment
@pytest.mark.skip()
def test_memory_data_sets_absent(kedro_context, configure_matrix_project):
    """Tests no MemoryDataSets are created."""

    used_data_sets = set.union(*[_pipeline_datasets(p) for p in pipelines.values()])

    used_data_sets_wout_double_params = {
        x.replace("params:params:", "params:") for x in used_data_sets
    }

```

Commented out code should not be allowed (and we should have a CI-integrated linter that prevents it from being committed). Why? In 90% of cases, it will remain in the codebase for years to come as a cargo cult that everyone is afraid to touch because "it might be needed for something". If it is very important to restore this code line after some work is completed, it should be mentioned in an appropriate issue.

## Comments that don’t add anything / GPT'd comments

This repeats the function name almost word-for-word.

```python
def test_run_subprocess_no_streaming_error(mock_popen):
    # Mock subprocess.run for non-streaming case with error
    with patch("subprocess.run") as mock_run:
        mock_run.side_effect = subprocess.CalledProcessError(
            returncode=1, cmd="test", output="", stderr="error"
        )
```

or

```python
# Test for submit command
def test_submit(mock_dependencies):
    runner = CliRunner()
    result = runner.invoke(submit, ["--username", "testuser"])
    assert result.exit_code == 0
    assert "Workflow submitted successfully!" in result.output

```
or

Name of the function and type annotations should make its purpose clear. If a comment is needed to explain it, it is too complicated and should be refactored.

`matrix/pipelines/matrix/src/matrix/cli_commands/submit.py`

```python
"""Command line tools for manipulating a Kedro project.

Intended to be invoked via `kedro`.
"""
# NOTE: This file was partially generated using AI assistance.

import json
import logging
import re
```
### Comments that could have been functions

`matrix/pipelines/matrix/src/matrix/cli_commands/submit.py` 

```python
def check_dependencies(verbose: bool):
    """Check and set up gcloud and kubectl dependencies.

    This function verifies that gcloud and kubectl are installed and properly configured.
    If kubectl is not installed, it attempts to install it using gcloud components.

    Args:
        verbose (bool): If True, provides more detailed output.

    Raises:
        EnvironmentError: If gcloud is not installed or kubectl cannot be configured.
    """
    if not command_exists("gcloud"):
        raise EnvironmentError("gcloud is not installed. Please install it first.")

    if not command_exists("kubectl"):
        console.print("kubectl is not installed. Installing it now...")
        run_subprocess("gcloud components install kubectl")

    # Authenticate gcloud
    active_account = (
        run_subprocess(
            "gcloud auth list --filter=status:ACTIVE --format=value'(ACCOUNT)'",
            capture_output=True,
            stream_output=verbose,
        )
        .stdout.strip()
        .split("\n")[0]
    )

    if not active_account:
        console.print("Authenticating gcloud...")
        run_subprocess("gcloud auth login", stream_output=verbose)

    # Configure kubectl
    project = "mtrx-hub-dev-3of"
    region = "us-central1"
    cluster = "compute-cluster"

    # Check if kubectl is already authenticated
    try:
        run_subprocess("kubectl get nodes", capture_output=True, stream_output=verbose)
        console.print("kubectl is already authenticated.")
    except subprocess.CalledProcessError:
        console.print("Authenticating kubectl...")
        run_subprocess(
            f"gcloud container clusters get-credentials {cluster} --project {project} --region {region}"
        )

    # Verify kubectl
    try:
        run_subprocess("kubectl get ns", capture_output=True, stream_output=verbose)
    except subprocess.CalledProcessError:
        raise EnvironmentError(
            "kubectl is not working. Please check your configuration."
        )
```

should be something like:

```python
def check_dependencies(verbose: bool):
    """Check and set up gcloud and kubectl dependencies.

    This function verifies that gcloud and kubectl are installed and properly configured.
    If kubectl is not installed, it attempts to install it using gcloud components.

    Args:
        verbose (bool): If True, provides more detailed output.

    Raises:
        EnvironmentError: If gcloud is not installed or kubectl cannot be configured.
    """
    if not command_exists("gcloud"):
        raise EnvironmentError("gcloud is not installed. Please install it first.")

    if not command_exists("kubectl"):
        install_kubectl(verbose)

    authenticate_gcloud(verbose)
    configure_kubectl(verbose)

def install_kubectl(verbose: bool):
    """Install kubectl if it is not already installed."""
    console.print("kubectl is not installed. Installing it now...")
    run_subprocess("gcloud components install kubectl", stream_output=verbose)

def authenticate_gcloud(verbose: bool):
    """Authenticate gcloud if not already authenticated."""
    active_account = (
        run_subprocess(
            "gcloud auth list --filter=status:ACTIVE --format=value'(ACCOUNT)'",
            capture_output=True,
            stream_output=verbose,
        )
        .stdout.strip()
        .split("\n")[0]
    )

    if not active_account:
        console.print("Authenticating gcloud...")
        run_subprocess("gcloud auth login", stream_output=verbose)

def configure_kubectl(verbose: bool):
    """Configure kubectl and authenticate if needed."""
    project = "mtrx-hub-dev-3of"
    region = "us-central1"
    cluster = "compute-cluster"

    if not is_kubectl_authenticated(verbose):
        authenticate_kubectl(cluster, project, region, verbose)

    verify_kubectl(verbose)

def is_kubectl_authenticated(verbose: bool) -> bool:
    """Check if kubectl is already authenticated."""
    try:
        run_subprocess("kubectl get nodes", capture_output=True, stream_output=verbose)
        console.print("kubectl is already authenticated.")
        return True
    except subprocess.CalledProcessError:
        return False

def authenticate_kubectl(cluster: str, project: str, region: str, verbose: bool):
    """Authenticate kubectl using gcloud."""
    console.print("Authenticating kubectl...")
    run_subprocess(
        f"gcloud container clusters get-credentials {cluster} --project {project} --region {region}",
        stream_output=verbose
    )

def verify_kubectl(verbose: bool):
    """Verify if kubectl is working."""
    try:
        run_subprocess("kubectl get ns", capture_output=True, stream_output=verbose)
    except subprocess.CalledProcessError:
        raise EnvironmentError("kubectl is not working. Please check your configuration.")
```
