### ISSUE TITLE
Collate, review and compare initial results from each algorithm recreated in Every Cure environment and gather feedback

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#470]
**Aim:**
- Review and compare initial treats prediction scores from across algorithms 

**Description:**
- Sub-contractors have been asked to generate treats predictions across the full matrix of drug-disease pairs 
- We will compare initial results to see if there are any trends/similarities across groups, with the caveat that all groups have used different KGs, ground truths and inputs meaning we cannot compare directly 

**Tasks which need to be completed:**
- [x] Confirm which inputs, ground truth, KG was used for each algorithm 
- [x] Identify which drug-disease pairs were used for training for each algorithm 
- [x] Compare drug-disease pair predictions across algorithms (e.g., top 500, average scores, distributions)

**This Sprint Goal is completed when:**
-  We have an excel sheet collated with top results from each workstream
