### ISSUE TITLE
Prioritise LLM use cases, select proof of concept use case and define necessary architecture

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#471]
**Aim:**
- Identify priority LLM use cases across working groups (Data & KGs, Modelling & Evaluation, Validation)
- Select top priority use case(s) to develop proof of concept 
- Create plan for implementing proof of concept 

**Description:**
- LLMs could be utilised for various uses across working groups. We need to understand what those use cases are and prioritise those that will have most impact
- Once identified, we need to select the top priority use cases to conduct a proof of concept and define the architecture needed
- Once defined, we will need to create a plan, detailing how we will implement the proof of concept  

**Tasks which need to be completed:**
- [x] Collate list of potential LLM use cases across Data & KGs, Modelling & Evaluation and Validation working groups
- [x] Identify priority use cases
- [x] Define necessary architecture
- [x] Develop plan detailing how we will develop POC

**This Sprint Goal is completed when:**
- We have a defined plan in detailing how we will implement the necessary architecture to create a POC
