### ISSUE TITLE
Review experiment proposals submitted by sub-contractors and select priority experiments 

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#475]
_October sprint goal - updated in comments_
_Previous title: Define prioritized next steps and create implementation plan for experimenting and improving Treats prediction algorithm_

**Aim:**
- Create an implementation plan detailing experiments and approaches we will trial to improve the treats prediction algorithm 

**Description:**
- To create a state of the art treats prediction algorithm, we need to experiment with different approaches and new methods
- Each sub-contractor has particular areas of expertise, which we will utilise to come up with a plan of the key experiments we should try over the next 6-9 months in attempt to improve the existing treats prediction algorithms
- It is important to take input from all Every Cure and sub-contractor team members, as well as external literature, to make sure we are making use of all skills and previous experiences 

**Tasks which need to be completed:**
- [x] Subs present their opinions of the most promising approaches at e.g., knowledge sharing session 
- [x] Hold brainstorming working sessions (with subs) to create list of ideas for experimentation over the next 6-9 months
- [ ] Sub contractors submit experiment proposal documents
- [ ] Prioritize experiments and create plan of when we aim to start and complete each experiment and who is responsible

**This Sprint Goal is completed when:**
- We have a defined list of prioritized experiments related to the treats prediction algorithm that we wish to undertake over the next 6-9 months, including when we plan to start and complete each and named responsible person/people
