### ISSUE TITLE
Define set of prioritized experiments for improving MoA algorithm 

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#477]
_October sprint goal - updated for November in comments
Previous title: Develop plan for improving baseline MoA algorithm_

**Aim:**
- Create an implementation plan detailing experiments and approaches we will trial to improve the MoA algorithm

**Description:**
- To create a state of the art MoA algorithm, we need to experiment with different approaches and new methods
- Each sub-contractor has particular areas of expertise, which we will utilise to come up with a plan of the key experiments we should try over the next 6-9 months in attempt to improve the existing MoA algorithm
- It is important to take input from all Every Cure and sub-contractor team members, as well as external literature, to make sure we are making use of all skills and previous experiences

**Tasks which need to be completed:**
- [ ] Subs present their opinions how we define MoA e.g., at knowledge sharing session
- [ ] Discuss in working session with Medical team what is important to them for determining MoA 
- [ ] Incorporate feedback from Medical team
- [ ] Conduct  and write-up literature review (potential for publishing)
- [ ] Hold brainstorming working sessions (with subs) to create list of ideas for experimentation over the next 6-9 months
- [ ] Prioritize experiments and create plan of when we aim to start and complete each experiment and who is responsible

**This Sprint Goal is completed when:**
- We have a defined list of prioritized experiments related to the MoA algorithm that we wish to undertake over the next 6-9 months, including when we plan to start and complete each and named responsible person/people
