### ISSUE TITLE
Generate MoA evaluation suite metrics as part of E2E run 

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#478]
**Aim:**
- Push MoA prediction evaluation suite to main branch so included in overall pipeline 

**Description:**
- We have created a MoA prediction algorithm. We must define the necessary evaluation metrics to assess performance of the algorithm 
- Once we have defined the necessary metrics, we must implement the evaluation suite and include it in the overall matrix pipeline 

**Tasks which need to be completed:**
- [x] Define subset of evaluation suite applicable to MoA 
- [x] Generate MoA prediction evaluation suite metrics as part of E2E run

**This Sprint Goal is completed when:**
- [x] MoA prediction evaluation suite metrics are generated as part of an E2E run
