### ISSUE TITLE
Recapitulate TxGNN model in notebook based on original paper (spans both Treats and MoA WSs)

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#479]
**Aim:**
- Recreate the TxGNN model based on original publication

**Description:**
- The TxGNN model represents another existing algorithm that predicts whether a drug treats a disease, plus potential MoA. It also has cross validation and evaluation metrics built in 
- We wish to recreate this model in the EC environment, using our drug and disease lists, ground truth and KG
- The first step of this is to become familiar with the original code and recapitulate it in a notebook, before starting to build core aspects in the EC environment 

**Tasks which need to be completed:**
- [x] Recapitulate TxGNN model using the data and code provided by publication in the kedro environment
- [x] Implement the existing metrics evaluation methods (e.g., hit@k, recall@N, mrr) for TxGNN
- [x] Analyze the results in the juyter notebook and figure out any potential issues

**This Sprint Goal is completed when:**
-  We have recreated the TxGNN model in Jupyter notebook using existing data associated with original publication
