### ISSUE TITLE
Define disease grouping strategy for disease split stratification

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#482]
**Aim:**
- Define categories for grouping diseases in order to perform disease split stratification  

**Description:**
- To assess model performance, we wish to perform disease split stratification cross validation 
- This requires diseases to be grouped at a higher level, meaning all related diseases are bundled together and can be removed as one entity
- As a first step, we must define the strategy we will use to split similar diseases into groups (e.g., neurodegenerative diseases)
**Tasks which need to be completed:**
- [x] Define initial disease split based on TxGNN paper
- [x] Test with Medical team
- [x] Refine grouping based on Medical team feedback
- [x] Finalise grouping strategy for disease split stratification 

**This Sprint Goal is completed when:**
- Grouping strategy for disease split stratification is finalised
