### ISSUE TITLE
Integrate ROBOKOP with RTX-KG2

### ISSUE THREAD

**Issue by capasfield** [everycure-org/matrix#485]
**Aim:**
Merge RTX and ROBOKOP in preliminary data contract format

**Description:**
In order to have one unified knowledge graph, we need the graphs that are ingested to align according to the data schema and the QC checks. The first step is to map 2 graphs together to solidify the normalization process.

This task will involve multiple para-programming sessions with Jason and Pascal.

**Tasks which need to be completed:**

- [X] Create notebook (first pass) that utilizes NodeNorm across edges and merges inputs using pandas data frames (Jason) #462
- [X] Add code for identifying duplicates (Jason - #306)
- [X] Convert Python script to Python function to be used in Kedro (Jason and Pascal)
- [ ] ~~Create a smaller testbed KG ("Tiny Graph") to enable streamlined testing (Joseph- #348 )~~

**This Sprint Goal is completed when:**
Pipeline able to start with ingested files from each KG, meet the data spec in the API, and result in a merged graph in Big Query

**Enables the following, but not necessarily part of October sprint**

- [x] #406

Documentation covered in #27
