### ISSUE TITLE
Ingest and Integrate SPOKE

### ISSUE THREAD

**Issue by capasfield** [everycure-org/matrix#486]
**Aim:**
Ingest the SPOKE Graph.

**Description:**
The SPOKE graph contains both proprietary and accessible data.  During the month of October we will begin the ingestion process for the SPOKE graph with the intent to have it fully ingested by mid-November. In order to complete this task, we need to identify a process for handling proprietary data. 

**Tasks which need to be completed:**
- [x] Upload SPOKE KG file (Charlotte)
- [ ] Write pipeline to move SPOKE into BigQuery (Jason)
- [ ] Hold discussions and formulate a plan on how to handle proprietary data. 
- [ ] https://github.com/everycure-org/matrix/issues/849 (missing nodes & point at right version)

**This Sprint Goal is completed when:**
SPOKE files have been ingested and integrated in Matrix repo. We have the start of a plan on how to handle proprietary graphs.
