### ISSUE TITLE
Finish synonymization and labelling improvements of drug list

### ISSUE THREAD

**Issue by capasfield** [everycure-org/matrix#490]
**Aim:**
Reach next version of drug list

**Description:**
The drug list has been growing to include drugs from many sources (FDA approved, approved in Europe, approved in Japan, etc). Several first steps have been made towards synonymization to eliminate duplicates. This task to incorporate 

**Tasks which need to be completed:**

- [ ] Improve synonymization approach to remove instances of "SID" drugs appearing in the MATRIX generation
- [ ] Reduce duplicates as much as is reasonably possible
- [x] Produce an "other_IDs" drugs list field which includes all synonymized IDs (at a minimum this must include ChEMBL), in addition to the primary ID field which will likely be CHEBI or RXCUI

**This Sprint Goal is completed when:**
New drugs list version published and taken up the Every Cure pipeline with no SID matches, and other_IDs field included with at least a ChEMBL ID
