### ISSUE TITLE
Compare utility of new ground truth lists vs. baseline from KGML-xDTD 

### ISSUE THREAD

**Issue by capasfield** [everycure-org/matrix#491]
**Aim:**

**Description:**
THIS TASK WILL REQUIRE COORDINATION ACROSS WORKSTREAMS!  
Now that we have several versions of ground truth, we need to compare the performance of the full pipeline if we hold all other variables constant between training models.
Ground truth versions to compare are 

1. Baseline ground truths from KGML-xDTD
2. Indication list + contraindications list
3. Downfilled indications list + contraindications list

**Tasks which need to be completed:**

- [x] Complete contraindications list in [matrix-indications-list](https://github.com/everycure-org/matrix-indication-list) (Marcello)
- [ ] Define the optimal ground-truth lists for modelling
- [ ] Document model performance results of experiment in MLFlow

**This Sprint Goal is completed when:**
 Comparable pipeline runs for all 3 versions of ground truth lists executed, with results available on MLFlow to review
...
