### ISSUE TITLE
Node and Edge Validation and Comprehensive QC Metrics

### ISSUE THREAD

**Issue by eKathleenCarter** [everycure-org/matrix#543]
**Aim:**
Implement the first node and edge validation steps—reference issues #83  and #488.

**Description:**
The aim is to track and record metrics surrounding node (Node Normalizer) and edge (Biolink Model) validation. This would run after a KG is ingested and after KGs are integrated. We will track node and edge processing throughout the pipeline, capturing normalization, failures,  and node-edge relationship metrics.

A suggested format for logging is below: 
 ```
"normalizations": {
                "2.3.17_v4.2.1_1.2_strict": {
                    "normalization_status": "stable",
                    "normalization_metadata": null,
                    "normalization_time": "10-22-24 19:07:01",
                    "supplementations": {
                        "1.0": {
                            "supplementation_status": "stable",
                            "supplementation_time": "10-22-24 19:07:07"
                        }
                    },
                    "node_normalization_version": "2.3.17",
                    "edge_normalization_version": "v4.2.1",
                    "strict_normalization": true,
                    "conflation": false,
                    "normalization_info": {
                        "strict_normalization": true,
                        "sequence_variants_pre_normalized": false,
                        "regular_node_norm_version": "2.3.17",
                        "regular_nodes_pre_norm": 8068,
                        "regular_node_norm_failures": 36,
                        "regular_nodes_post_norm": 8032,
                        "all_nodes_post_norm": 8032,
                        "merged_nodes_post_norm": 0,
                        "final_normalized_nodes": 8032,
                        "edge_norm_version": "v4.2.1",
                        "source_edges": 53432,
                        "edges_failed_due_to_nodes": 197,
                        "edges_failed_due_to_predicates": 0,
                        "edge_mergers": 10488,
                        "edge_splits": 0,
                        "subclass_loops_removed": 0,
                        "final_normalized_edges": 42747,
                        "unconnected_nodes_removed": 1492
                    }
                }

        ],
        "predicate_totals": {
            "biolink:treats": 9290,
            "biolink:contraindicated_in": 26562,
            "biolink:applied_to_treat": 1953,
            "biolink:preventative_for_condition": 1,
            "biolink:diagnoses": 1,
            "biolink:has_adverse_event": 205133,
            "biolink:affects": 18992,
            "biolink:directly_physically_interacts_with": 4145,
            "biolink:related_to": 784,
            "biolink:physically_interacts_with": 7,
            "biolink:subclass_of": 414051
        },
        "predicates_by_knowledge_source": {
            "infores:drugcentral": {
                "biolink:treats": 9290,
                "biolink:contraindicated_in": 26562,
                "biolink:applied_to_treat": 1953,
                "biolink:preventative_for_condition": 1,
                "biolink:diagnoses": 1,
                "biolink:affects": 5642,
                "biolink:directly_physically_interacts_with": 255,
                "biolink:related_to": 782,
                "biolink:physically_interacts_with": 4
            },
            "infores:faers": {
                "biolink:has_adverse_event": 205133
            },
            "infores:chembl": {
                "biolink:affects": 11230,
                "biolink:directly_physically_interacts_with": 3848,
                "biolink:physically_interacts_with": 1,
                "biolink:related_to": 2
            },
            "infores:gtopdb": {
                "biolink:affects": 1299,
                "biolink:directly_physically_interacts_with": 42
            },
            "infores:pdsp": {
                "biolink:affects": 734
            },
            "infores:kegg": {
                "biolink:affects": 25
            },
            "infores:drugbank": {
                "biolink:affects": 62,
                "biolink:physically_interacts_with": 2
            },
            "infores:ubergraph": {
                "biolink:subclass_of": 414051
            }
        },
        "node_curie_prefixes": {
            "PUBCHEM.COMPOUND": 509,
            "MONDO": 19762,
            "UMLS": 15572,
            "UNII": 303,
            "CHEBI": 5725,
            "HP": 13379,
            "NCIT": 11128,
            "DrugCentral": 8,
            "CHEMBL.COMPOUND": 20,
            "DOID": 27,
            "MESH": 2,
            "NCBITaxon": 17,
            "UniProtKB": 8041,
            "PR": 9119,
            "OMIM": 15
        },
```
...

**Tasks which need to be completed:**
Implement tracking for the following metrics:

- [ ] Number of edges that are valid  (Biolink Model)
- [ ] Log of invalid edges and why they were flagged as invalid
- [ ] Track node-edge relationships (count Subject-Predicate-Object tripels)

Note - a valid edge has the following properties: subject, predicate, object, knowledge_level, agent_type, primary_knowledge_source
...

**This Sprint Goal is completed when:**

- [ ] We can log all the metrics, failures, and passes described above.
- [ ] Mapping files for node and edge normalizations are generated and stored for future reference.

...
----------------------------------------------------------------------------------------------------------------------
SAVE THESE METRICS FOR A FUTURE SPRINT: 
- Number of nodes ingested
- Number of nodes normalized (via Node Normalizer)
- Number of nodes that failed normalization
- Log of nodes that failed normalization
- Node to Normalized Node map
- Number of edges ingested
- Number of edges not valid (Biolink Model)
- Count of node types and edge types
- Identify unconnected nodes and nodes removed post-normalization
