### ISSUE TITLE
Complete E2E run across each algorithm using EC KG and evaluation suite

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#581]
*November sprint goal - updated for January in comments
Original title: Generate treats prediction scores for the full matrix for each algorithm from each institution using V1 combined KG*

**Aim:**

* Generate treats prediction scores for all drug-disease pairs in the Every Cure starting drug and disease lists across all algorithms using the V1 combined knowledge graph

**Description:**

* In November, WG1 will create V1 of the combined KG (including RTXKG2, ROBOKOP and SPOKE)
* Sub-contractors will be asked to rerun their full matrix predictions using the combined KG

**Tasks which need to be completed:**

- [X] Access V1 combined KG
- [X] Generate prediction scores for every drug-disease pair within the matrix from every algorithm
- [X] Submit full matrix results [here](https://drive.google.com/drive/folders/1Jo2z_fE2RFZmYI4o694LSKKjft3IfE85)

**This Sprint Goal is completed when:**
Each sub-contractor submits full prediction results to allocated Google drive folder
