### ISSUE TITLE
Train, validate and evaluate performance of TxGNN model using EC KG and ground truth 

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#586]
**Aim:**
- Generate prediction results using the TxGNN model and Every Cure data inputs

**Description:**
- The TxGNN model represents another existing algorithm that predicts whether a drug treats a disease, plus potential MoA. It also has cross validation and evaluation metrics built in
- We wish to recreate this model in the EC environment, using our drug and disease lists, ground truth and KG
- We have recapitulate the TxGNN model in a notebook and built core aspects in the EC environment in issue #479 
- Our next step is to retrain the model on Every Cure data

**Tasks which need to be completed:**
- [x] Apply TxGNN architecture to the KG2 (Train TxGNN using Every Cure data)
- [x] Compare results to other model outputs
- [x] Review everything with data science team and make sure all look good 

 **This Sprint Goal is completed when:**
We have generated results using the TxGNN and Every Cure KG, drug and disease lists and Ground Truth, which have passed through the Every Cure evaluation suite to evaluate performance
