### ISSUE TITLE
Define drug grouping strategy for drug split stratification 

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#591]
**Aim:**
- Define categories for grouping drugs in order to perform drug split stratification

**Description:**
- To assess model performance, we wish to perform drug split stratification cross validation
- This requires drugs to be grouped at a higher level, meaning all related drugs are bundled together and can be removed as one entity
- As a first step, we must define the strategy we will use to split similar drugs into groups 

**Tasks which need to be completed:**
- [x] Define initial drug split
- [x] Test with Medical team 
- [ ] Refine grouping based on Medical team feedback 
- [ ] Finalise V1 grouping strategy for drug split stratification 

**This Sprint Goal is completed when:**
V1 grouping strategy for drug split stratification is finalised
