### ISSUE TITLE
Assess stability of end-to-end runs

### ISSUE THREAD

**Issue by leelancashire** [everycure-org/matrix#595]
**Aim:**

Conduct end-to-end (E2E) runs across multiple configurations to comprehensively evaluate treat scores. This analysis will help estimate model stability by assessing prediction consistency when key components of the pipeline are modified.

**Description:**

The hypothesis is that each stage of the pipeline—embedding models, classifiers, and input data—significantly impacts prediction outcomes. Currently, we can alternate between different embedding models and classifiers. This issue aims to evaluate how these variations influence predictions, determining whether they yield consistent outcomes and identifying any drug-disease pairs that are stable repurposing candidates (i.e., consistently highly ranked) across multiple configurations.

**Tasks which need to be completed:**

Complete successful E2E runs for the following configurations:

- [x] **EC Current Baseline Configuration**: Input = rtx-kg2 (v2.7.3); Embedding = OpenAI + GraphSAGE; Model = XGB Ensemble 
- [x] Input = rtx-kg2 (v2.7.3); Embedding = Node2Vec; Model = XGB Ensemble
- [x] Input = rtx-kg2 (v2.7.3); Embedding = PubMedBERT + GraphSAGE; Model = XGB Ensemble
- [x] Input = rtx-kg2 (v2.7.3); Embedding = OpenAI + GraphSAGE; Model = Random Forest
- [x] Input = rtx-kg2 (v2.7.3); Embedding = Node2Vec; Model = Random Forest
 -[ ] **Publication Baseline**: Input = rtx-kg2 (v2.7.3); Embedding = PubMedBERT + GraphSAGE; Model = Random Forest

**This Sprint Goal is completed when:**

- [ ] Generate the final set of predictions using the analysis previously developed by @drhodesbrc.
- [ ] Develop an additional evaluation metric, such as `commonality@k`, to assess the consistency of top-k predictions across configurations. Refer to prior work by @alexeistepa.

** Related to:**
https://github.com/everycure-org/matrix/issues/301
https://github.com/everycure-org/matrix/issues/470
