### ISSUE TITLE
ArgoNode Improvements

### ISSUE THREAD

**Issue by matwasilewski** [everycure-org/matrix#652]
**Is your feature request related to a problem? Please describe.**
This is an umbrella issue for follow-up tasks after adding ArgoNode.

**Tasks**
- [x] Enforce use of ArgoNode. Standard Kedro Node should no longer be allowed. See comment: https://github.com/everycure-org/matrix/pull/626#discussion_r1838274263
- [x] Move all pipelines to ArgoNode
- [x] K8s compute resources defined only per-task (rather than in one default shared by the full `kedro` template)
- [ ] DryRun reevaluation
- [ ] Remove defaults from Argo Template: https://github.com/everycure-org/matrix/pull/626#discussion_r1842088685
- [ ] Add predefined S, M, L, XL node packages: https://github.com/everycure-org/matrix/pull/626#discussion_r1832552703
- [x] Conduct a full run with GPUs
- [ ] Document how to use GPUs in the pipelines
