### ISSUE TITLE
Compare E2E runs across each algorithm using EC KG and evaluation suite 

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#719]
_December sprint goal originally - carried over to March with same details and completion criteria_
**Aim:**
- Compare prediction outputs from each algorithm, as well as performance across Every Cure evaluation metrics 

**Description:**
- Subcontractors have been tasked with completing E2E runs #581 
- We will compare the outputs of these runs, examining both prediction outputs and evaluation metrics

**Tasks which need to be completed:**
- [ ]  Compare drug-disease pair predictions across algorithms (e.g., top 500, average scores, distributions) - can use method developed for stability measurements from November
- [ ] Compare evaluation suite outputs across algorithms 
- [ ] Share results of comparison of E2E runs across institutional algorithms using EC KG and evaluation suite 

**This Sprint Goal is completed when:**
Summary comparisons are generated across algorithms and shared with all
