### ISSUE TITLE
Finalize methods for ARPA-H milestone 6 report and baseline treats prediction publication

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#727]
*December sprint goal - updated for January in comments
Original title: Draft V1 methods for ARPA-H Milestone 6 report and baseline treats prediction publication*
**Aim:**
Start writing up methodology for ARPA-H Milestone 6 report and proposed baseline treats prediction publication

**Description:**

* We are required to complete a report for ARPA-H Milestone 6 - "Completion of report on the quantification of performance metrics for the 5 algorithms"

This report compares predictions across each of the the institutional algorithms

* We must write up the appropriate methodology for each of the instutional algorithms
* We would like to also publicjh our baseline results, hence we will adapt the ARPA-H report into a publication for submission to a scientific journal

**Tasks which need to be completed:**

- [X] Share with sub-contractors skeleton structure of ARPA-H report and baseline treats publication
- [X] Inform team members of their assigned sections and requirements
- [ ] Draft V1 of methods for inclusion in ARPA-H milestone 6 report
- [ ] Amend V1 of methods for ARPA-H milestone 6 report to create V1 of methods for baseline treats publication

**This Sprint Goal is completed when:**
All relevant team members have completed V1 their methodology for report and publication
