### ISSUE TITLE
Finalize disease masking for TxGNN model using EC KG

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#732]
_December sprint goal - updated for January in comments
Original title: Trial disease masking for TxGNN model using EC KG_
**Aim:**
Experiment with disease masking with TxGNN to determine effectiveness of zero shot repurposing using RTXKG2

**Description:**
We have have worked to implement the TxGNN model based on KG2 in the Kedro environment.

Next, we would want to do the following experiments:
     a.  Evaluate TxGNN model by comparing it with KGML-xDTD using EC's evaluation metrics (to conduct a fair comparison, both models need to adopt the same input KG and the same data split sets. The only difference is the method).
     b. Trial of the disease-area masking approach from the original TxGNN paper to assess the zero-shot repurposing performance for both models.

**Tasks which need to be completed:**
- [x] Run KGML-xDTD and TxGNN model on same filtered/simplified KG and compare outputs 
- [x] Add disease categorization to KG #482 
- [x] Implement disease masking methods for both KGML-xDTD and TxGNN models
- [x] Compare both models for the zero-shot performance
 
**This Sprint Goal is completed when:**
We have generated results for disease masking using TxGNN model and RTXKG2 baseline
