### ISSUE TITLE
Develop rudimentary UI tool for sharing predictions with Medical Team

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#869]
**Aim:**
Develop an interim tool for sharing holistic MATRIX outputs with Every Cure Medical Team to allow them to fully assess drug:disease pair results

**Description:**

* It is important for the Medical Team to be able to interrogate the MATRIX predictions without needing to go via one of the Tech Team
* We are in the process of developing a visualisation tool with Thoughtworks, but this will still take some months
* We will therefore create an interim tool that can be used internally by the Medical Team until the public facing tool is ready

**Tasks which need to be completed:**

- [X] Conduct Hackathon to understand user needs and design and develop tool to provide full prediction results with Every Cure Med Team
- [ ] Finalize tool and publish, ready for accepting results
- [X] Share first round of results with Med Team in new tool
- [X] Collect feedback from Med Team
- [ ] Refine tool based on feedback

**This Sprint Goal is completed when:**
We have developed a working tool for sharing MATRIX prediction results with the Medical Team
