### ISSUE TITLE
Develop method to perform disease split validation prototype

### ISSUE THREAD

**Issue by RobynMac25** [everycure-org/matrix#876]
_Carried over to March due to Chunyu leave period_
**Aim:**
Develop pipeline compatible approach for disease-split validation 

**Description:**
- Part of our ARPA-H deliverables require us to perform disease-split validation
- We have already defined and incorporated the disease split grouping strategy in #737 
- We must now experiment with to create a prototype of the disease split methodology 

**Tasks which need to be completed:**
- [x] Plan disease-split validation approach
- [x] Develop pipeline compatible disease-split validation working prototype 
- [x] Complete E2E run excluding identified disease categories and compare prediction results to Every Cure baseline  
- [ ] Submit summary report of results, comparing to EC baseline and TxGNN

**This Sprint Goal is completed when:**
We have developed a pipeline compatible working prototype of disease-split validation which can be tested and later impended in the pipeline
